analDirs = {'/BEEF02/smm/sm9614_Analysis/analysis02/',...
            '/BEEF02/smm/sm9608_Analysis/analysis02',...
            '/BEEF01/smm/sm9601_Analysis/analysis03/'...
            '/BEEF01/smm/sm9603_Analysis/analysis04/'}

        
fileExtCell = {'.eeg';...
          '_LinNearCSD121.csd';...
          %'_NearAveCSD1.csd';...
          '_LinNear.eeg'};

      
for j=1:length(fileExtCell)
    for k=1:length(analDirs)
        cd(analDirs{k})
        GlmPartialAnalysisBatch01('CalcRunningSpectra9_noExp','secondRun',LoadVar('AlterFiles'),fileExtCell{j},{'speed.p0','accel.p0'})
    end
end



analDirs = {...
            '/BEEF02/smm/sm9614_Analysis/analysis02/',...
            '/BEEF02/smm/sm9608_Analysis/analysis02',...
            '/BEEF01/smm/sm9601_Analysis/analysis03/'...
            '/BEEF01/smm/sm9603_Analysis/analysis04/'...
            }
 fileExtCell = {...
                '_LinNearCSD121.csd',...
                }
            
for j=1:length(fileExtCell)
    for k=1:length(analDirs)
        cd(analDirs{k})
        GlmWholeAnalysisBatch03('CalcRunningSpectra9_noExp','Alter_Vs_Control_EachRegion','firstRun',{'MazeFiles'},fileExtCell{j},{'speed.p0','accel.p0'})
    end
end


analDirs = {...
            '/BEEF02/smm/sm9614_Analysis/analysis02/',...
            '/BEEF02/smm/sm9608_Analysis/analysis02',...
            '/BEEF01/smm/sm9601_Analysis/analysis03/'...
            '/BEEF01/smm/sm9603_Analysis/analysis04/'...
            }
 fileExtCell = {...
                '_LinNearCSD121.csd',...
                }

for j=1:length(fileExtCell)
    for k=1:length(analDirs)
        cd(analDirs{k})
        GlmPartialAnalysisBatch03('CalcRunningSpectra9_noExp','Alter_Vs_Control_EachRegion','firstRun',{'MazeFiles'},fileExtCell{j},{'speed.p0','accel.p0'})
    end
end
    



for k=1:length(analDirs)
    cd([analDirs{k} '/TrialDesig/GlmWholeModel03'])
    load Alter_Vs_Control_EachRegion.mat
    modelSpec = modelSpec([3:5],[3:4])
    save('Alter_Vs_Control_EachRegion.mat','adjDayMedBool','modelSpec','outlierDepth','trialDesig','trialMeanBool')
end





analDirs = {...
            '/BEEF02/smm/sm9614_Analysis/analysis02/',...
            '/BEEF02/smm/sm9608_Analysis/analysis02',...
            '/BEEF01/smm/sm9601_Analysis/analysis03/'...
            '/BEEF01/smm/sm9603_Analysis/analysis04/'...
            }
 fileExtCell = {...
                '.eeg',...
                '_LinNearCSD121.csd',...
                }

for j=1:length(fileExtCell)
    for k=1:length(analDirs)
        cd(analDirs{k})
        GlmPartialAnalysisBatch03('CalcRunningSpectra9_noExp','Alter','groupAnal1',{'MazeFiles'},fileExtCell{j},{'speed.p0','accel.p0'})
    end
end

for j=1:length(fileExtCell)
    for k=1:length(analDirs)
        cd(analDirs{k})
        GlmWholeAnalysisBatch03('CalcRunningSpectra9_noExp','Alter','groupAnal1',{'MazeFiles'},fileExtCell{j},{'speed.p0','accel.p0'})
    end
end


analDirs = {...
            '/BEEF02/smm/sm9614_Analysis/analysis02/',...
            '/BEEF02/smm/sm9608_Analysis/analysis02',...
            '/BEEF01/smm/sm9601_Analysis/analysis03/'...
            '/BEEF01/smm/sm9603_Analysis/analysis04/'...
            }
 fileExtCell = {...
                '.eeg',...
                '_LinNearCSD121.csd',...
                }
analRoutine = {...
                'Alter_S0_A0',...
                'Alter_Vs_Control_EachRegion_S0_A0',...
                'Alter_Right_Vs_Left_S0_A0',...
                };
for m=1:length(analRoutine)
    for j=1:length(fileExtCell)
        for k=1:length(analDirs)
            cd(analDirs{k})
            GlmPartialAnalysisBatch04('CalcRunningSpectra9_noExp',analRoutine{m},'01',{'MazeFiles'},fileExtCell{j})
        end
    end
end

for m=1:length(analRoutine)
    for j=1:length(fileExtCell)
        for k=1:length(analDirs)
            cd(analDirs{k})
            GlmWholeAnalysisBatch04('CalcRunningSpectra9_noExp',analRoutine{m},'01',{'MazeFiles'},fileExtCell{j})
        end
    end
end

