#! /bin/sh
#  reconfig
#    Runs configure scripts

DEFAULT_OPTS="--prefix=$HOME/load5_v1.1.2 --exec-prefix=$HOME/load5_v1.1.2"

cd build-cygwin

MATLAB_OPTS="--with-matlab=/C/matlab6p5"
export PKG_CONFIG_PATH="$HOME/matio_v1.1.2/lib/pkgconfig:$PKG_CONFIG_PATH"

CC=gcc \
CFLAGS='-v -O3 -g -ffast-math -malign-double -mms-bitfields -Wall -pedantic -mno-cygwin -fPIC -fexceptions' \
LDFLAGS='-Wl,-s -fexceptions' \
../configure $DEFAULT_OPTS $MATLAB_OPTS

if test $? = 0
then
    make
fi

if test $? = 0
then
    make install
fi 

cd ..
