pwd
fileExtCell = {'.eeg','_LinNearCSD121.csd'};
for k=1:length(fileExtCell)
    fileExt = fileExtCell{k};
    fprintf('\n%s\n',fileExt);

    chanLoc = Struct2CellArray(LoadVar(['ChanInfo/ChanLoc_Min' fileExt]),[],1);
    badChan = load(['ChanInfo/BadChan' fileExt '.txt']);
    for j=1:size(chanLoc,1)
        nPerLay = length(find(setdiff([chanLoc{j,2}{:}],badChan)));
        fprintf('%s: %i\n',chanLoc{j,1},nPerLay)
    end
end



analRoutine = {...
     'AlterGood_S0_A0_RL_MRrctg',...
}
depVarCell = {...
'unitACG.rate'}  
fileBaseCell = LoadVar('FileInfo/AlterFiles')
spectAnalDir = {...
    'CalcRunningSpectra12_noExp_MidPoints_MinSpeed0Win626wavParam8',...
    }
dirName = [spectAnalDir{1} fileExtCell{1}] 
fileExtCell = {'.eeg','_LinNearCSD121.csd'};
load(['TrialDesig/GlmWholeModel08/' analRoutine{1}])
        trialDesig.rl.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 1 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.rl.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 1 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.rl.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 1 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.rl.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 1 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };
        trialDesig.lr.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 1 0 0 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.lr.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 1 0 0 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.lr.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 1 0 0 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.lr.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 1 0 0 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };

        trialDesig.rl.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.rl.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.rl.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.rl.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };
        trialDesig.lr.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.lr.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.lr.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.lr.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };

animal = 'sm9603';
cd /BEEF02/smm/sm9608_Analysis/7-17-04/analysis/
animal = 'sm9608';
cd /BEEF02/smm/sm9614_Analysis/4-17-05/analysis/
animal = 'sm9614';

load(['TrialDesig/GlmWholeModel08/' analRoutine{1}])


cd /BEEF01/smm/sm9603_Analysis/3-21-04/analysis/
animal = 'sm9603';
cd /BEEF02/smm/sm9608_Analysis/7-17-04/analysis/
animal = 'sm9608';
cd /BEEF02/smm/sm9614_Analysis/4-17-05/analysis/
animal = 'sm9614';
 

load(['TrialDesig/GlmWholeModel08/' analRoutine{1}])
       trialDesig.rl.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.rl.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.rl.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.rl.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[0 0 1 0 0 0 1 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };
        trialDesig.lr.returnArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','returnArm'}}...
            };
        trialDesig.lr.centerArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','centerArm'}}...
            };
        trialDesig.lr.Tjunction = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','Tjunction'}}...
            };
        trialDesig.lr.goalArm = {...
            {{'taskType','alter'},...
            {'trialType',[1 0 0 0 1 0 0 0 0 0 0 0 0],'>',0.6},...
            {'mazeLocName','goalArm'}}...
            };

analRoutine = {...
     'AlterGood_S0_A0_RL_MRrctg',...
}
depVarCell = {...
'unitACG.rate'}  
fileBaseCell = LoadVar('FileInfo/AlterFiles')
spectAnalDir = {...
    'CalcRunningSpectra12_noExp_MidPoints_MinSpeed0Win626wavParam8',...
    }
dirName = [spectAnalDir{1} fileExtCell{1}] 
fileExtCell = {'.eeg','_LinNearCSD121.csd'};


rate = Struct2CellArray(LoadDesigVar(fileBaseCell,dirName,depVarCell{1},trialDesig),[],1);

cType = LoadCellTypes([fileBaseCell{1} '/' fileBaseCell{1} '.type']);
cLayer = LoadCellLayers([fileBaseCell{1} '/' fileBaseCell{1} '.cellLayer']);

caData = find(strcmp(rate(:,2),'centerArm'));
caRate = cat(1,rate{caData,end});
alpha = 0.05;
signif = alpha/size(cType,1);
%signif = alpha;

figure(1)
clf
clf 
hold on
for j=1:size(caRate,2)
%     pST(j) = signtest(caRate(:,j));
    pRS(j) = min([signtest(rate{caData(1),end}(:,j)),signtest(rate{caData(2),end}(:,j))]);
    plot(log10(pST),'k:')
    if pST(j)<signif
    text(j,log10(pST(j)),[cLayer(j,3), cType(j,3)],'color',[0 1 0])
    else
        text(j,log10(pST(j)),[cLayer(j,3), cType(j,3)],'color',[0 0 1])
    end
end

sm9603
signif
1 - ca3x
1 - orn
1 - hilx
1 - grann
1 - moln
marginal
2 - ca1w 
1 - ca3w

sm9608
signif
4 - ca1w
1  -hilx
1 - grann
1 - orn
1 - hiln
marginal
4 - ca1w
1 - ca3w

sm9614
signif
3 - ca3w
1 - grann
marginal
2 - ca3w

figure(2)
clf
clf 
hold on
for j=1:size(caRate,2)
    pRS(j) = ranksum(rate{caData(1),end}(:,j),rate{caData(2),end}(:,j));
    plot(log10(pRS),'k:')
    if pRS(j)<signif
    text(j,log10(pRS(j)),[cLayer(j,3), cType(j,3)],'color',[1 0 0])
    else
        text(j,log10(pRS(j)),[cLayer(j,3), cType(j,3)],'color',[0 0 1])
    end
end
for j=1:size(caRate,2)
    pRS(j) = hist(rate{caData(1),end}(:,j),rate{caData(2),end}(:,j));
    plot(log10(pRS),'k:')
    if pRS(j)<signif
    text(j,log10(pRS(j)),[cLayer(j,3), cType(j,3)],'color',[1 0 0])
    else
        text(j,log10(pRS(j)),[cLayer(j,3), cType(j,3)],'color',[0 0 1])
    end
end

pVals.(animal).pST = pST;
pVals.(animal).pRS = pRS;
signif = alpha/30
animal = 'sm9603';
 sum((pVals.(animal).pRS<signif))/sum((pVals.(animal).pST<signif))
 
animal = 'sm9608';
 sum((pVals.(animal).pRS<signif))/sum((pVals.(animal).pST<signif))
animal = 'sm9614';
 sum((pVals.(animal).pRS<signif))/sum((pVals.(animal).pST<signif))
