function ConvertSelChanFormat(analDirs,spectAnalBase)

convertFiles = {...
    'cohSpec',...
    'crossSpec',...
    'gammaCohMean40-100Hz',...
    'gammaCohMedian40-100Hz',...
    'gammaPhaseMean40-100Hz',...
    'phaseSpec',...
    'thetaCohMean4-12Hz',...
    'thetaCohMedian4-12Hz',...
    'thetaPhaseMean4-12Hz',...
}

for j=1:length(analDirs)
    for k=1:length(fileExtCell)
    selChan = LoadVar([analDirs{j} 'ChanInfo/SelChan' fileExtCell{k});
    
    for m=1:length(convertFiles)
        