function GlmWholeAnalysisBatch08(spectAnalDir,analRoutine,nameNote,fileExt,depVarCell,varargin)
%function GlmWholeAnalysisBatch08(spectAnalDir,analRoutine,nameNote,fileExt,varargin)
% GlmWholeAnalysisBatch05('CalcRunningSpectra9_noExp','Alter','secondRun',LoadVar('AlterFiles'),'_LinNear.eeg',{'speed.p0','accel.p0'})
% spectAnalDir = 'CalcRunningSpectra9_noExp';
% analRoutine = 'Alter_Vs_Circle_CompSimRegions'
% nameNote = 'Test';
% files = LoadVar('AlterFiles');
% files = [LoadVar('AlterFiles');LoadVar('CircleFiles')];
% fileExt = '_LinNear.eeg';
% indepVarCell = {'speed.p0','accel.p0'};
% varargin = DefaultArgs(varargin,{[]});

chanDir = 'ChanInfo/';
chanMat = LoadVar([chanDir 'ChanMat' fileExt '.mat']);
selChans = fieldnames(LoadVar([chanDir 'SelChan' fileExt '.mat']));


nchan = max(max(chanMat));

if ~isempty(intersect(depVarCell,'powSpec.yo'))
    temp = [{0,nchan,1},varargin];
    GlmWholeModel08(spectAnalDir,analRoutine,nameNote,fileExt,'powSpec.yo',temp{:})
end

intersectCell = {...
    'thetaPowPeak4-12Hz',...
    'thetaPowIntg4-12Hz',...
    'thetaPowLMPeak4-12Hz',...
    'thetaPowPeak6-12Hz',...
    'thetaPowIntg6-12Hz',...
    'thetaPowLMPeak6-12Hz',...
    'gammaPowIntg40-100Hz',...
    'gammaPowIntg40-120Hz',...
    'gammaPowIntg50-100Hz',...
    'gammaPowIntg50-120Hz',...
    'gammaPowIntg60-120Hz',...
    'thetaFreq6-12Hz',...
    'thetaFreq4-12Hz',...
    'thetaFreqLM6-12Hz',...
    };
for j=1:length(depVarCell)
    if ~isempty(intersect(depVarCell{j},intersectCell))
        GlmWholeModel08(spectAnalDir,analRoutine,nameNote,fileExt,depVarCell{j},0,nchan,0,varargin)
    end
end

for j=1:length(selChans)
    if ~isempty(intersect(depVarCell,'cohSpec.yo'))
        GlmWholeModel08(spectAnalDir,analRoutine,nameNote,fileExt,['cohSpec.yo.' selChans{j}],0,nchan,1,varargin)
    end
    
  intersectCell = {...
        'thetaCohMean4-12Hz',...
        'thetaCohMean6-12Hz',...
        'thetaCohWavMean4-12Hz',...
        'thetaCohLMPeak4-12Hz',...
        'thetaCohLMPeak6-12Hz',...
        'thetaCohWavLMPeak4-12Hz',...
        'gammaCohMean60-120Hz',...
        'gammaCohMean40-100Hz',...
        'gammaCohMean40-120Hz',...
        'gammaCohMean50-100Hz',...
        'gammaCohMean50-120Hz',...
        'gammaCohWavMean40-120Hz',...
        };
    for k=1:length(depVarCell)
        if ~isempty(intersect(depVarCell{k},intersectCell))
            GlmWholeModel08(spectAnalDir,analRoutine,nameNote,fileExt,[depVarCell{k} '.' selChans{j}],0,nchan,0,varargin)
        end
    end
    
    intersectCell = {...
        'thetaPhaseMean4-12Hz',...
        'thetaPhaseLMPeak4-12Hz',...
        'thetaPhaseMean6-12Hz',...
        'thetaPhaseLMPeak6-12Hz',...
        'gammaPhaseMean40-100Hz',...
        'gammaPhaseMean40-120Hz',...
        'gammaPhaseMean60-120Hz',...
    };
    for k=1:length(depVarCell)
        if ~isempty(intersect(depVarCell{k},intersectCell))
            GlmWholeModel08(spectAnalDir,analRoutine,nameNote,fileExt,[depVarCell{k} '.' selChans{j}],1,nchan,0,varargin)
        end
    end
end
