function GlmWholeAnalysisBatch07(dataDescription,analRoutine,nameNote,fileExt,depVarCell,varargin)
%function GlmWholeAnalysisBatch07(dataDescription,analRoutine,nameNote,fileExt,varargin)
% GlmWholeAnalysisBatch05('CalcRunningSpectra9_noExp','Alter','secondRun',LoadVar('AlterFiles'),'_LinNear.eeg',{'speed.p0','accel.p0'})
% dataDescription = 'CalcRunningSpectra9_noExp';
% analRoutine = 'Alter_Vs_Circle_CompSimRegions'
% nameNote = 'Test';
% files = LoadVar('AlterFiles');
% files = [LoadVar('AlterFiles');LoadVar('CircleFiles')];
% fileExt = '_LinNear.eeg';
% indepVarCell = {'speed.p0','accel.p0'};
% varargin = DefaultArgs(varargin,{[]});

chanDir = 'ChanInfo/';
chanMat = LoadVar([chanDir 'ChanMat' fileExt '.mat']);
selChansStruct = LoadVar([chanDir 'SelChan' fileExt '.mat']);
anatFields = fieldnames(selChansStruct);
for j=1:length(anatFields)
    selChans(j) = selChansStruct.(anatFields{j});
end

nchan = max(max(chanMat));

if ~isempty(intersect(depVarCell,'powSpec.yo'))
    GlmWholeModel07(dataDescription,analRoutine,nameNote,fileExt,'powSpec.yo',[{0,nchan,1},varargin])
end
intersectCell = {...
    'thetaPowPeak4-12Hz',...
    'thetaPowIntg4-12Hz',...
    'thetaPowPeak6-12Hz',...
    'thetaPowIntg6-12Hz',...
    'gammaPowIntg40-100Hz',...
    'gammaPowIntg40-120Hz',...
    'gammaPowIntg50-100Hz',...
    'gammaPowIntg50-120Hz',...
    'gammaPowIntg60-120Hz',...
    }
for j=1:length(depVarCell)
    if ~isempty(intersect(depVarCell{j},intersectCell))
        GlmWholeModel07(dataDescription,analRoutine,nameNote,fileExt,depVarCell{j},[{0,nchan,0},varargin])
    end
end

for j=1:length(selChans)
    selChanName = ['.ch' num2str(selChans(j))];
    if ~isempty(intersect(depVarCell,'cohSpec.yo'))
        GlmWholeModel07(dataDescription,analRoutine,nameNote,fileExt,['cohSpec.yo' selChanName],[{0,nchan,1},varargin])
    end
    
    intersectCell = {...
        'thetaCohMean4-12Hz',...
        'thetaCohMean6-12Hz',...
        'gammaCohMean60-120Hz',...
        'gammaCohMean40-100Hz',...
        'gammaCohMean40-120Hz',...
        'gammaCohMean50-100Hz',...
        'gammaCohMean50-120Hz',...
        };
    for k=1:length(depVarCell)
        if ~isempty(intersect(depVarCell{k},intersectCell))
            GlmWholeModel07(dataDescription,analRoutine,nameNote,fileExt,[depVarCell{k} selChanName],[{0,nchan,0},varargin])
        end
    end
    
    intersectCell = {...
        'thetaPhaseMean4-12Hz',...
        'thetaPhaseMean6-12Hz',...
        'gammaPhaseMean40-100Hz',...
        'gammaPhaseMean60-120Hz',...
    };
    for k=1:length(depVarCell)
        if ~isempty(intersect(depVarCell{k},intersectCell))
            GlmWholeModel07(dataDescription,analRoutine,nameNote,fileExt,[depVarCell{k} selChanName],[{1,nchan,0},varargin])
        end
    end
end
