



title_page(1)=figure('Color','w','NumberTitle','off','Name',...
	'EZTOOLS',...
	'Units','Normalized',...
        'Menubar','none',...
	'Position',[.2 .4 .45 .4]);
hold on
	load ezlogo
	image(X);colormap(map);clear X map; 
	axis([0 650 -200 200]); axis off; 
	set(gca,'Units','Normalized','Ydir','Reverse',...
        'Position',[.05    0.400    0.5000    1.2]);
	


 title_page(2)=uicontrol(title_page(1),'Style','Push','String','OK',...
		'Units','Normalized',...
		'Position',[.3 .02 .2 .07],...
		'CallBack','delete(title_page(1))');

title_page(3)=uicontrol(title_page(1),'Style','Push','String','Help',...
		'Units','Normalized',...
		'Position',[.6 .02 .2 .07],...
		'CallBack','scrledit(''init'',[.01 .1 .9 .9],readstr(''readme.eza''))');







text(.95,.30,'ools',...
        'color',[0 0 0],...
	'FontName','Roman',...
	'FontAngle','normal',...
	'FontWeight','demi',...
	'Fontsize',50,...
	'Units','Normalized');

H=axes('position',[0 0 1 .5]);
set(H,'visible','off');
text(.1,.9,'Toolbox for Matlab, Ver 5.XX',...
        'color',[0 0 0],...
	'FontName','Roman',...
	'FontAngle','Italic',...
	'FontWeight','demi',...
	'Fontsize',15,...
	'Units','Normalized');

text(.1,.7,'Version: 1.0 , Oct, 1997',...
        'color',[0 0 0],...
	'FontName','SanSerif',...
	'FontAngle','Normal',...
	'FontWeight','Normal',...
	'Fontsize',10,...
	'Units','Normalized');


text(.03,.50,'Author: Capt. Richard G. Cobb',...
        'color',[0 0 0],...
	'FontName','SanSerif',...
	'FontAngle','Normal',...
	'FontWeight','Bold',...
	'Fontsize',10,...
	'Units','Normalized');



text(.1,.3,'Air Force Research Laboratory/VSDV',...
        'color',[0 0 0],...
	'FontName','SanSerif',...
	'FontAngle','Normal',...
	'FontWeight','Normal',...
	'Fontsize',10,...
   'Units','Normalized');




