%CalcCohPeakBat01
analDirs = {...
    '/BEEF02/smm/sm9614_Analysis/analysis02/',...
    '/BEEF02/smm/sm9608_Analysis/analysis02',...
    '/BEEF01/smm/sm9601_Analysis/analysis03/'...
    '/BEEF01/smm/sm9603_Analysis/analysis04/'...
    }
fileExtCell = {...
    '.eeg',...
    '_LinNearCSD121.csd',...
    '_NearAveCSD1.csd',...
    }
thetaFreqRange = [6 12];

for j=1:length(analDirs)
    cd(analDirs{j})
    CalcCohPeak01(LoadVar('MazeFiles'),fileExtCell,thetaFreqRange);
end
return



