%adminfunc/eeg_helpadmin.m() - Help file for EEGLAB

function noname();

command = { ...
'pophelp(''eeg_checkset.m'');' ...
'pophelp(''eeg_global.m'');' ...
'pophelp(''eeg_helpadmin.m'');' ...
'pophelp(''eeg_helphelp.m'');' ...
'pophelp(''eeg_helpmenu.m'');' ...
'pophelp(''eeg_helppop.m'');' ...
'pophelp(''eeg_helpsigproc.m'');' ...
'pophelp(''eeg_options.m'');' ...
'pophelp(''eeg_retrieve.m'');' ...
'pophelp(''eeg_store.m'');' ...
'pophelp(''eeglab.m'');' ...
'pophelp(''pop_delset.m'');' ...
'pophelp(''pop_editoptions.m'');' ...
'pophelp(''pop_rejmenu.m'');' ...
};
text = { ...
'eeg_checkset.m' ...
'eeg_global.m' ...
'eeg_helpadmin.m' ...
'eeg_helphelp.m' ...
'eeg_helpmenu.m' ...
'eeg_helppop.m' ...
'eeg_helpsigproc.m' ...
'eeg_options.m' ...
'eeg_retrieve.m' ...
'eeg_store.m' ...
'eeglab.m' ...
'pop_delset.m' ...
'pop_editoptions.m' ...
'pop_rejmenu.m' ...
};
textgui( text, command,'fontsize', 15, 'fontname', 'times', 'linesperpage', 18, 'title',strvcat( 'Admin functions', '(Click on blue text for help)'));
icadefs; set(gcf, 'COLOR', BACKCOLOR);h = findobj('parent', gcf, 'style', 'slider');set(h, 'backgroundcolor', GUIBACKCOLOR);return;
